# Generated by Django 5.2.9 on 2026-02-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='booked_on',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='stadium_image_url',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Premium', 'Premium'), ('VIP', 'VIP')], default='General', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='price_general',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='match',
            name='price_premium',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='match',
            name='price_vip',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats_booked',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='available_seats',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='match',
            name='total_seats',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stadium'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='myapp.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='myapp.team'),
        ),
    ]
