# Generated by Django 5.2.9 on 2026-02-06 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_stadium_team_rename_booking_date_booking_booked_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='available_seats',
        ),
        migrations.AlterField(
            model_name='match',
            name='total_seats',
            field=models.IntegerField(default=60),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('General', 'General'), ('Premium', 'Premium'), ('VIP', 'VIP')], max_length=20)),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='myapp.match')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(to='myapp.seat'),
        ),
    ]
